// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddURLRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	CustomEndpoint       string   `protobuf:"bytes,2,opt,name=customEndpoint,proto3" json:"customEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddURLRequest) Reset()         { *m = AddURLRequest{} }
func (m *AddURLRequest) String() string { return proto.CompactTextString(m) }
func (*AddURLRequest) ProtoMessage()    {}
func (*AddURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *AddURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURLRequest.Unmarshal(m, b)
}
func (m *AddURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURLRequest.Marshal(b, m, deterministic)
}
func (m *AddURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURLRequest.Merge(m, src)
}
func (m *AddURLRequest) XXX_Size() int {
	return xxx_messageInfo_AddURLRequest.Size(m)
}
func (m *AddURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddURLRequest proto.InternalMessageInfo

func (m *AddURLRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddURLRequest) GetCustomEndpoint() string {
	if m != nil {
		return m.CustomEndpoint
	}
	return ""
}

type AddURLResponse struct {
	Status               string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url                  *ShortenedURL `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddURLResponse) Reset()         { *m = AddURLResponse{} }
func (m *AddURLResponse) String() string { return proto.CompactTextString(m) }
func (*AddURLResponse) ProtoMessage()    {}
func (*AddURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *AddURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURLResponse.Unmarshal(m, b)
}
func (m *AddURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURLResponse.Marshal(b, m, deterministic)
}
func (m *AddURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURLResponse.Merge(m, src)
}
func (m *AddURLResponse) XXX_Size() int {
	return xxx_messageInfo_AddURLResponse.Size(m)
}
func (m *AddURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddURLResponse proto.InternalMessageInfo

func (m *AddURLResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AddURLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddURLResponse) GetUrl() *ShortenedURL {
	if m != nil {
		return m.Url
	}
	return nil
}

type ShortenedURL struct {
	OriginalURL          string   `protobuf:"bytes,1,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	ShortenedURL         string   `protobuf:"bytes,2,opt,name=shortenedURL,proto3" json:"shortenedURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenedURL) Reset()         { *m = ShortenedURL{} }
func (m *ShortenedURL) String() string { return proto.CompactTextString(m) }
func (*ShortenedURL) ProtoMessage()    {}
func (*ShortenedURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *ShortenedURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenedURL.Unmarshal(m, b)
}
func (m *ShortenedURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenedURL.Marshal(b, m, deterministic)
}
func (m *ShortenedURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenedURL.Merge(m, src)
}
func (m *ShortenedURL) XXX_Size() int {
	return xxx_messageInfo_ShortenedURL.Size(m)
}
func (m *ShortenedURL) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenedURL.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenedURL proto.InternalMessageInfo

func (m *ShortenedURL) GetOriginalURL() string {
	if m != nil {
		return m.OriginalURL
	}
	return ""
}

func (m *ShortenedURL) GetShortenedURL() string {
	if m != nil {
		return m.ShortenedURL
	}
	return ""
}

type GetURLRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetURLRequest) Reset()         { *m = GetURLRequest{} }
func (m *GetURLRequest) String() string { return proto.CompactTextString(m) }
func (*GetURLRequest) ProtoMessage()    {}
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetURLRequest.Unmarshal(m, b)
}
func (m *GetURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetURLRequest.Marshal(b, m, deterministic)
}
func (m *GetURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetURLRequest.Merge(m, src)
}
func (m *GetURLRequest) XXX_Size() int {
	return xxx_messageInfo_GetURLRequest.Size(m)
}
func (m *GetURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetURLRequest proto.InternalMessageInfo

func (m *GetURLRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type GetURLResponse struct {
	Url                  []*ShortenedURL `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetURLResponse) Reset()         { *m = GetURLResponse{} }
func (m *GetURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetURLResponse) ProtoMessage()    {}
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *GetURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetURLResponse.Unmarshal(m, b)
}
func (m *GetURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetURLResponse.Marshal(b, m, deterministic)
}
func (m *GetURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetURLResponse.Merge(m, src)
}
func (m *GetURLResponse) XXX_Size() int {
	return xxx_messageInfo_GetURLResponse.Size(m)
}
func (m *GetURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetURLResponse proto.InternalMessageInfo

func (m *GetURLResponse) GetUrl() []*ShortenedURL {
	if m != nil {
		return m.Url
	}
	return nil
}

func init() {
	proto.RegisterType((*AddURLRequest)(nil), "proto.AddURLRequest")
	proto.RegisterType((*AddURLResponse)(nil), "proto.AddURLResponse")
	proto.RegisterType((*ShortenedURL)(nil), "proto.ShortenedURL")
	proto.RegisterType((*GetURLRequest)(nil), "proto.GetURLRequest")
	proto.RegisterType((*GetURLResponse)(nil), "proto.GetURLResponse")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x6e, 0x88, 0x08, 0xe2, 0x9a, 0x46, 0xe8, 0xf8, 0x51, 0xc4, 0x14, 0x2c, 0x15, 0x75, 0xea,
	0x50, 0x86, 0xce, 0x0c, 0x08, 0x21, 0x65, 0x0a, 0xe4, 0x01, 0x42, 0x73, 0x2a, 0x91, 0xda, 0x38,
	0xf8, 0x1c, 0x66, 0x1e, 0x1d, 0x25, 0xb1, 0x4b, 0xdc, 0xa1, 0x93, 0xef, 0xbe, 0xf3, 0xf7, 0xe3,
	0x33, 0x44, 0x4c, 0xea, 0xa7, 0xda, 0x10, 0x2f, 0x1b, 0x25, 0xb5, 0xc4, 0xf3, 0xfe, 0x10, 0x6f,
	0x30, 0x7b, 0x2e, 0xcb, 0x3c, 0x4b, 0x33, 0xfa, 0x6e, 0x89, 0x35, 0x5e, 0x81, 0xdf, 0xaa, 0x5d,
	0xec, 0x25, 0xde, 0xe2, 0x32, 0xeb, 0x4a, 0x7c, 0x84, 0x68, 0xd3, 0xb2, 0x96, 0xfb, 0x97, 0xba,
	0x6c, 0x64, 0x55, 0xeb, 0xf8, 0xac, 0x1f, 0x1e, 0xa1, 0xa2, 0x82, 0xc8, 0x4a, 0x71, 0x23, 0x6b,
	0x26, 0xbc, 0x83, 0x80, 0x75, 0xa1, 0x5b, 0x36, 0x72, 0xa6, 0xc3, 0x18, 0x2e, 0xf6, 0xc4, 0x5c,
	0x6c, 0xc9, 0x48, 0xd9, 0x16, 0xe7, 0x83, 0xbb, 0x9f, 0x78, 0x8b, 0xe9, 0xea, 0x7a, 0x88, 0xba,
	0x7c, 0xff, 0x92, 0x4a, 0x53, 0x4d, 0xbd, 0x76, 0x37, 0x17, 0x1f, 0x10, 0x8e, 0x41, 0x4c, 0x60,
	0x2a, 0x55, 0xb5, 0xad, 0xea, 0x62, 0x97, 0x67, 0xa9, 0x71, 0x1b, 0x43, 0x28, 0x20, 0xe4, 0x11,
	0xc3, 0xf8, 0x3a, 0x98, 0x78, 0x80, 0xd9, 0x2b, 0x69, 0x77, 0x17, 0xff, 0x72, 0x5d, 0x29, 0xd6,
	0x10, 0xd9, 0x2b, 0xe6, 0x8d, 0x73, 0xbb, 0x2f, 0xff, 0x54, 0xe2, 0xd5, 0xaf, 0x07, 0x61, 0x9e,
	0xa5, 0x76, 0xa0, 0x70, 0x0d, 0xc1, 0xb0, 0x2d, 0xbc, 0x31, 0x24, 0xe7, 0x1f, 0xee, 0x6f, 0x8f,
	0xd0, 0xc1, 0x4e, 0x4c, 0x3a, 0xe2, 0x10, 0xe1, 0x40, 0x74, 0x42, 0x1f, 0x88, 0x6e, 0x4e, 0x31,
	0xf9, 0x0c, 0x7a, 0xfc, 0xe9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x53, 0x36, 0xad, 0x0a, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// URLShortenerClient is the client API for URLShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type URLShortenerClient interface {
	AddURL(ctx context.Context, in *AddURLRequest, opts ...grpc.CallOption) (*AddURLResponse, error)
	GetURL(ctx context.Context, in *GetURLRequest, opts ...grpc.CallOption) (*GetURLResponse, error)
}

type uRLShortenerClient struct {
	cc *grpc.ClientConn
}

func NewURLShortenerClient(cc *grpc.ClientConn) URLShortenerClient {
	return &uRLShortenerClient{cc}
}

func (c *uRLShortenerClient) AddURL(ctx context.Context, in *AddURLRequest, opts ...grpc.CallOption) (*AddURLResponse, error) {
	out := new(AddURLResponse)
	err := c.cc.Invoke(ctx, "/proto.URLShortener/AddURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) GetURL(ctx context.Context, in *GetURLRequest, opts ...grpc.CallOption) (*GetURLResponse, error) {
	out := new(GetURLResponse)
	err := c.cc.Invoke(ctx, "/proto.URLShortener/GetURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLShortenerServer is the server API for URLShortener service.
type URLShortenerServer interface {
	AddURL(context.Context, *AddURLRequest) (*AddURLResponse, error)
	GetURL(context.Context, *GetURLRequest) (*GetURLResponse, error)
}

// UnimplementedURLShortenerServer can be embedded to have forward compatible implementations.
type UnimplementedURLShortenerServer struct {
}

func (*UnimplementedURLShortenerServer) AddURL(ctx context.Context, req *AddURLRequest) (*AddURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddURL not implemented")
}
func (*UnimplementedURLShortenerServer) GetURL(ctx context.Context, req *GetURLRequest) (*GetURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetURL not implemented")
}

func RegisterURLShortenerServer(s *grpc.Server, srv URLShortenerServer) {
	s.RegisterService(&_URLShortener_serviceDesc, srv)
}

func _URLShortener_AddURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).AddURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.URLShortener/AddURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).AddURL(ctx, req.(*AddURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_GetURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).GetURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.URLShortener/GetURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).GetURL(ctx, req.(*GetURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _URLShortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.URLShortener",
	HandlerType: (*URLShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddURL",
			Handler:    _URLShortener_AddURL_Handler,
		},
		{
			MethodName: "GetURL",
			Handler:    _URLShortener_GetURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
